"""initial_migration

Revision ID: 9529212d8c6b
Revises: 
Create Date: 2026-08-06 02:08:56.554886

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9529212d8c6b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_table('drone_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.String(), nullable=True),
    sa.Column('command_type', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('issued_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drone_commands_drone_id'), 'drone_commands', ['drone_id'], unique=False)
    op.create_index(op.f('ix_drone_commands_id'), 'drone_commands', ['id'], unique=False)
    op.create_table('drones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_command', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drones_drone_id'), 'drones', ['drone_id'], unique=True)
    op.create_index(op.f('ix_drones_id'), 'drones', ['id'], unique=False)
    op.create_table('geofence_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zone_type', sa.String(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofence_zones_id'), 'geofence_zones', ['id'], unique=False)
    op.create_index(op.f('ix_geofence_zones_name'), 'geofence_zones', ['name'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.String(), nullable=True),
    sa.Column('attack_type', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('threat_level', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('shap_values', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_drone_id'), 'incidents', ['drone_id'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('critical_threshold', sa.Float(), nullable=True),
    sa.Column('high_threshold', sa.Float(), nullable=True),
    sa.Column('refresh_rate', sa.String(), nullable=True),
    sa.Column('ui_sound', sa.Boolean(), nullable=True),
    sa.Column('push_notif', sa.Boolean(), nullable=True),
    sa.Column('webhooks', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drone_id', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('packet_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at')
    )
    op.create_index(op.f('ix_telemetry_logs_created_at'), 'telemetry_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_drone_id'), 'telemetry_logs', ['drone_id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_id'), 'telemetry_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###
    op.execute("SELECT create_hypertable('telemetry_logs', 'created_at', if_not_exists => TRUE);")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_telemetry_logs_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_drone_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_created_at'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_drone_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_geofence_zones_name'), table_name='geofence_zones')
    op.drop_index(op.f('ix_geofence_zones_id'), table_name='geofence_zones')
    op.drop_table('geofence_zones')
    op.drop_index(op.f('ix_drones_id'), table_name='drones')
    op.drop_index(op.f('ix_drones_drone_id'), table_name='drones')
    op.drop_table('drones')
    op.drop_index(op.f('ix_drone_commands_id'), table_name='drone_commands')
    op.drop_index(op.f('ix_drone_commands_drone_id'), table_name='drone_commands')
    op.drop_table('drone_commands')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
